### ISSUE TITLE
Vibration Test does not work under Firmware 3.5

### ISSUE THREAD

**Issue by chasedaigle** [raphnet/gc_n64_usb-v3#1]
In windows 10 when using the 2.1.5 raphnet-tech adapter manager and with an adapter updated with the 3.5 version of the firmware the vibration test does not function.  When trying the same adapter but with the 3.4 firmware loaded the vibration test functions on a standard DOL-003 controller but not on a wavebird DOL-004 controller.  Trying older firmware yields the same results as 3.4.

**Comment by raphnet** [comment]
I just tested version 3.5 + manager 2.1.5 + Windows 10. It works here at least.
The test vibration button only tests vibration on the "player 1" controller. Wavebird controllers do not support vibration, so if you had a Wavebird connected there when you first tried it with firmware 3.5, that could explain why it did not work. Can you reinstall firmware 3.5, connect two wired controllers and try using the button again? The one that will vibrate is player 1. (In case the cables are mis-labeled)

**Comment by chasedaigle** [comment]
Firmware revision 3.5.1 addressed this issue.
