### ISSUE TITLE
Would it be possible to add support for the ATmega328?

### ISSUE THREAD

**Issue by Xii-Nyth** [raphnet/gc_n64_usb-v3#11]
Just thought Id ask since arduino unos are extremely common,  its also found on the pro mini

**Comment by Xii-Nyth** [comment]
Update: found out it has no default hid support but that theres firmware which adds it

**Comment by raphnet** [comment]
The Atmel AVR Atmega328 does not have a built-in USB controller, and this project requires AVRs with a built-in USB controller, such as the Atmega32u2 and at90usb1297. I could add support for other AVRs meeting this requirement, such as the ATmega32u4 for instance, but nothing can be done for "normal" non-USB AVRs.

**Comment by raphnet** [comment]
To build a N64/Gamecube to USB adapter with a regular AVR micro-controller, I would suggest that you look at my old project which was based on V-USB (software USB implementation) however USB runs at low speed and the latency is a bit higher:
https://github.com/raphnet/gc_n64_usb

(note: I have not tested, but this one should already work on Atmega328 if the firmware is built using the Makefile meant for Atmega168)
