### ISSUE TITLE
Changing Modes

### ISSUE THREAD

**Issue by Dignity1337** [raphnet/gc_n64_usb-v3#12]
Hi. I'm currently building one of the Raphnet GC/N64 to UISB V3 adapters using an Arduino Leonardo (ATmega32u4). Everything is working fine but I noticed an inconvenient behavior (maybe also not intened behavior or a bug) while changing modes. If I use the cmd to execute "gcn64ctl -f --set_mode 0" (Singleplayer) or "gcn64ctl -f --set_mode 16" (Dual Player), I need to disconnect and reconnect the USB cable to my PC so that the adapter gets recogniced correctly. I don't know if that is a bug or intended behavior but it would be definitely more conveniant if the change could be made without reconnecting the USB. Took me some hours to find this out. At first I thought it just wouldn't work at all (when executing the commands the only thing that changed inside the adapter manager were the adapter modes. But the adapter didn't actually used these modes until I learned that I had to reconnect).

**Comment by raphnet** [comment]
When using the command-line, use --reset to force the adapter to reboot into its new configuration. The adapter manager supports switching mode for some adapters and issues the reset command internally, so it's only one click. But on the command-line, well it's a manual extra step...

Just a though... Does the --reset command actually work on your Atemga32u4 setup? It's entirely possible that it does not!

**Comment by Dignity1337** [comment]
Thanks a lot. That works just as expected. It would probably be useful for other people if you would mention it on your website here under the section „Personalities and multiplayer modes“:
https://www.raphnet.net/electronique/gcn64_usb_adapter_gen3/index_en.php#9

**Comment by raphnet** [comment]
It is now mentioned, thank you for the suggestion!
