### ISSUE TITLE
Vibration doesn't work in Dolphin 5.0 9575

### ISSUE THREAD

**Issue by dezraj** [raphnet/gc_n64_usb-v3#4]
So, this Dolphin version is very updated but I can't seem to make the vibration work when setting up the GC controller in Dolphin.

I've tried all vibration methods available there (such as Sine, Ramp etc) and the test will never make the controller vibrate. Vibration works fine in the adapter manager testing though.

Is this a Dolphin issue?

Thanks in advance for any help.

**Comment by oscarbidabehere** [comment]
I have the same problem in version 9155. I just ordered this adapter and I cannot make the vibration work. In windows controller settings I cannot see anything related to force feedback, Is there something we have to enable somewhere or maybe update the firmware?

**Comment by oscarbidabehere** [comment]
@dezraj 
I tested with todays release (5.0-9680) and in the motor configuration I added all available methods concatenated with an OR operator, like this:
`Constant | Ramp | Square | Sine | Triangle | 'Sawtooth Up' | 'Sawtooth Down'`
When you try to test it it doesn't work, however during game it works perfectly. 
PD: I think that the dophin version is not important, the thing is that the test button is not working and that is very confusing but if you add the vibration methods it works.
