### ISSUE TITLE
Adding Bluetooth support?

### ISSUE THREAD

**Issue by matakko** [raphnet/gc_n64_usb-v3#9]
Hello awesome project!

I was wondering,
Will it be possible to integrate an esp32 chip to send inputs via Bluetooth like this project https://github.com/NathanReeves/BlueCubeMod ? 

I’m secretly dreaming of the ascii GameCube keyboard in Bluetooth ..

**Comment by raphnet** [comment]
It seems to me that rather than somehow linking an ESP32 to this project, it would make more sense to have the ESP32 drive the show completely (i.e. Use it's built-in IO to poll the Gamecube controller directly) since it probably powerful enough. But that's a completely different project.
